package com.excilys.computerdatabase.domain;

import java.sql.Timestamp;
import java.time.LocalDate;

/**
 * Class representing a computer.
 * @author Sylvain DESPREZ
 *
 */
public class Computer {

	/**
	 * Id of the computer (generated by the database).
	 */
	protected Long id;
	/**
	 * Name of the computer (should not be null or empty).
	 */
	protected String name;
	/**
	 * Date of introduction of the computer (optional)
	 */
	protected LocalDate introducedDate;
	/**
	 * Date of discontinuation of the computer (optional)
	 */
	protected LocalDate discontinuedDate;
	protected Company company;
	
	public Computer() {

	}

	public Computer(Long id, String name, LocalDate introducedDate,
			LocalDate discontinuedDate, Company company) {
		this.id = id;
		setName(name);
		this.introducedDate = introducedDate;
		this.discontinuedDate = discontinuedDate;
		this.company = company;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	/**
	 * Check if the name is null or is empty before setting the name
	 * @param name
	 */
	public void setName(String name) {
		if (name == null) {
			throw new RuntimeException("Name cannot be null");
		}
		name = name.trim();
		if (name.isEmpty()) {
			throw new RuntimeException("Name cannot be empty");
		}
		this.name = name;
	}

	public LocalDate getIntroducedDate() {
		return introducedDate;
	}

	public void setIntroducedDate(LocalDate introducedDate) {
		this.introducedDate = introducedDate;
	}

	/**
	 * Set the introducedDate of a computer using a Timestamp.
	 * @param introducedDate : the value of the introducedDate as a Timestamp 
	 */
	public void setIntroducedDate(Timestamp introducedDate) {
		if (discontinuedDate != null) {
			this.introducedDate = introducedDate.toLocalDateTime().toLocalDate();
		} else {
			this.introducedDate = null;
		}
	}

	public LocalDate getDiscontinuedDate() {
		return discontinuedDate;
	}

	/**
	 * Set the discontinuedDate of a computer using a Timestamp.
	 * @param discontinuedDate : the value of the discontinuedDate as a Timestamp 
	 */
	public void setDiscontinuedDate(LocalDate discontinuedDate) {
		this.discontinuedDate = discontinuedDate;
	}

	public void setDiscontinuedDate(Timestamp discontinuedDate) {
		if (discontinuedDate != null) {
			this.discontinuedDate = discontinuedDate.toLocalDateTime()
					.toLocalDate();
		} else {
			this.introducedDate = null;
		}

	}

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * @return Timestamp : the value of the introducedDate as a Timestamp 
	 */
	public Timestamp getIntroducedTimestamp() {
		if (introducedDate != null) {
			return Timestamp.valueOf(introducedDate.atStartOfDay());
		}
		return null;
	}

	
	/**
	 * @return Timestamp : the value of the discontinued as a Timestamp 
	 */
	public Timestamp getDiscontinuedTimestamp() {
		if (discontinuedDate != null) {
			return Timestamp.valueOf(discontinuedDate.atStartOfDay());
		}
		return null;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Computer other = (Computer) obj;
		if (id.compareTo(other.id) != 0) {
			return false;
		}
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer("Computer [id=").append(id)
				.append(", name=").append(name)
				.append(", introducedDate=").append(introducedDate)
				.append(", discontinuedDate=").append(discontinuedDate)
				.append(", company=").append(company).append("]");
		return buffer.toString();
	}

}
